# Generated by Django 4.2.7 on 2024-02-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='amount',
            field=models.PositiveIntegerField(default=1000, verbose_name='цена'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='amount',
            field=models.PositiveIntegerField(default=1000, verbose_name='цена'),
        ),
    ]
