# Generated by Django 4.2.7 on 2024-03-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_course_updated_lesson_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата и время обновления'),
        ),
    ]
